In [1]:
import numpy as np

# Solicitar la longitud del vector
n = int(input("Introduce la longitud de los vectores: "))

# Solicitar los vectores
vector1 = np.array([float(input(f"Introduce el elemento {i+1} del vector 1: ")) for i in range(n)])
vector2 = np.array([float(input(f"Introduce el elemento {i+1} del vector 2: ")) for i in range(n)])

# Calcular el producto escalar
producto_escalar = np.dot(vector1, vector2)

print(f"El producto escalar de los dos vectores es: {producto_escalar}")


Introduce la longitud de los vectores: 2
Introduce el elemento 1 del vector 1: 1
Introduce el elemento 2 del vector 1: 1
Introduce el elemento 1 del vector 2: 3
Introduce el elemento 2 del vector 2: 3
El producto escalar de los dos vectores es: 6.0


In [2]:
import numpy as np

# Función para solicitar una matriz
def solicitar_matriz(filas, columnas, nombre):
    print(f"Introduce los elementos de la matriz {nombre}:")
    matriz = []
    for i in range(filas):
        fila = [float(input(f"Elemento [{i+1},{j+1}]: ")) for j in range(columnas)]
        matriz.append(fila)
    return np.array(matriz)

# Solicitar dimensiones de las matrices
filas_A = int(input("Introduce el número de filas de la matriz A: "))
columnas_A = int(input("Introduce el número de columnas de la matriz A: "))
filas_B = int(input("Introduce el número de filas de la matriz B: "))
columnas_B = int(input("Introduce el número de columnas de la matriz B: "))

# Solicitar las matrices A y B
A = solicitar_matriz(filas_A, columnas_A, "A")
B = solicitar_matriz(filas_B, columnas_B, "B")

# Operación a: 3A
print("3A =\n", 3 * A)

# Operación b: 4B
print("4B =\n", 4 * B)

# Operación c: A + B (si tienen las mismas dimensiones)
if A.shape == B.shape:
    print("A + B =\n", A + B)
else:
    print("A + B no es posible, las matrices tienen diferentes dimensiones.")

# Operación d: B * A (multiplicación de matrices si las dimensiones son compatibles)
if B.shape[1] == A.shape[0]:
    print("B * A =\n", np.dot(B, A))
else:
    print("B * A no es posible, las dimensiones no son compatibles.")
4

Introduce el número de filas de la matriz A: 2
Introduce el número de columnas de la matriz A: 1
Introduce el número de filas de la matriz B: 4
Introduce el número de columnas de la matriz B: 3
Introduce los elementos de la matriz A:
Elemento [1,1]: 1
Elemento [2,1]: 2
Introduce los elementos de la matriz B:
Elemento [1,1]: 3
Elemento [1,2]: 4
Elemento [1,3]: 6
Elemento [2,1]: 7
Elemento [2,2]: 0
Elemento [2,3]: 7
Elemento [3,1]: 3
Elemento [3,2]: 4
Elemento [3,3]: 4
Elemento [4,1]: 4
Elemento [4,2]: 4
Elemento [4,3]: 4
3A =
 [[3.]
 [6.]]
4B =
 [[12. 16. 24.]
 [28.  0. 28.]
 [12. 16. 16.]
 [16. 16. 16.]]
A + B no es posible, las matrices tienen diferentes dimensiones.
B * A no es posible, las dimensiones no son compatibles.


In [3]:
import numpy as np

# Matriz aumentada
A = np.array([[1, 0, 1, 2.5],
              [3, 4, 3, 11.5],
              [4, 1, 0, 15]], dtype=float)

# Función para realizar la eliminación Gauss-Jordan
def gauss_jordan(A):
    filas, columnas = A.shape

    for i in range(filas):
        # Pivoteo: hacer que A[i, i] sea 1 dividiendo toda la fila i por A[i, i]
        A[i] = A[i] / A[i, i]

        # Eliminar los elementos en la columna i en otras filas
        for j in range(filas):
            if i != j:
                A[j] = A[j] - A[j, i] * A[i]

    return A

# Aplicar el método de Gauss-Jordan
solucion = gauss_jordan(A)

# Las soluciones están en la última columna de la matriz aumentada
x1, x2, x3 = solucion[:, -1]

print(f"Las soluciones son:\nx1 = {x1}\nx2 = {x2}\nx3 = {x3}")


Las soluciones son:
x1 = 3.5
x2 = 1.0
x3 = -1.0
